version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d


  nodeserver:
    image: course_node
    depends_on:
      - db
    build:
       context: .
    ports:
      - "3000:3000"
    command: sh -c "/wait && node index.js"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=15
      - WAIT_HOST_CONNECT_TIMEOUT=15


  nginx:
    image: course_nginx
    depends_on:
       - nodeserver
    restart: always
    build:
        context: ./nginx
    ports:
         - "8080:80"



